###################################################
# Summary tab details
# The below specifies the exact formatting and content for each column in the
# order presented. Each column is assumed to have a one row header. format
# specifies the format of data, while label_format specifies the format of
# the header row (which has text equal to the column label.)
#
# The formula field follows one of four forms:
# tbl:Label: drops in columns from the roster file (typically from 
# current_students.csv)
# =FORMULA: an Excel equation that can reference other columns in the same
# row using the %Label% convention, although %*% instead gets replaced
# with the value of summary_name (defined in the first row)
# cfg:Label: refers to a formula defined in the config (settings.yaml) file
# and might have a provision for campus-specific formulas in addition to a
# general standard one
# <id>:Label: for debugging, just copy the label id into data rows
#
# summary_name can be either Strats, Counselor, or Campus
#
summary_fields: # one of these is picked by summary_type in main settings.yaml
    Strategy:
        excel_name: Strats # named range being referenced on Students
        excel_label: Strategy # label for the column in this tab
        tbl_name: local_strategy # reference for the students table to summarize
    Counselor:
        excel_name: Counselor # named range being referenced on Students
        excel_label: Counselor # label for the column in this tab
        tbl_name: Counselor # reference for the students table to summarize
summary_columns:
    - summary_field: # this first column is special
        formula: tbl:sum_field # created based on summary_name
        format: right
        width: 15.0
        label_format: bold_olive_underline
        cond_format: solid_bottom_right
        sum_formula: ''
        sum_format: right
    - '# Students':
        formula: '=COUNTIF(%*%,%summary_field%)'
        format: centered
        width: 6.14
        label_format: bold_olive_underline
        cond_format: solid_bottom
        sum_formula: '=SUM(|# Students|)'
        sum_format: centered_summary
    - '':
        formula: '=%# Students%/@# Students@'
        format: single_percent_centered
        width: 5.43
        label_format: bold_olive_underline
        cond_format: single_percent_centered_solid_bottom
        sum_formula: '=%# Students%/@# Students@'
        sum_format: single_percent_centered_summary
    - '=TargetGRLabel&" Grad Rate"':
        formula: '=IF(%# Students%>0,SUMIF(%*%,%summary_field%,StudentTargets)/%# Students%,"")'
        format: single_percent_centered
        width: 8.57
        label_format: bold_yellow_center_wrap
        cond_format: single_percent_centered_solid_bottom
        sum_formula: '=SUMPRODUCT(|# Students|,|=TargetGRLabel&" Grad Rate"|)/@# Students@'
        sum_format: single_percent_centered_summary
    - '=IdealGRLabel&" Grad Rate"':
        formula: '=IF(%# Students%>0,SUMIF(%*%,%summary_field%,ReachStudentTargets)/%# Students%,"")'
        format: single_percent_centered_right
        width: 6.57
        label_format: bold_yellow_center_wrap_right
        cond_format: single_percent_centered_right_solid_bottom
        sum_formula: '=SUMPRODUCT(|# Students|,|=IdealGRLabel&" Grad Rate"|)/@# Students@'
        sum_format: single_percent_centered_summary_right
    - 'Predict-ion "Perfect"':
        formula: '=IF(%# Students%>0,SUMIF(%*%,%summary_field%,PredP)/%# Students%,"")'
        format: single_percent_centered
        width: 8.43h
        label_format: bold_red_center_wrap
        cond_format: single_percent_centered_solid_bottom
        sum_formula: '=SUMPRODUCT(|# Students|,|Predict-ion "Perfect"|)/@# Students@'
        sum_format: single_percent_centered_summary
    - 'Predict-ion "Minus 1"':
        formula: '=IF(%# Students%>0,SUMIF(%*%,%summary_field%,PredM1)/%# Students%,"")'
        format: single_percent_centered
        width: 9.43h
        label_format: bold_red_center_wrap
        cond_format: single_percent_centered_solid_bottom
        sum_formula: '=SUMPRODUCT(|# Students|,|Predict-ion "Minus 1"|)/@# Students@'
        sum_format: single_percent_centered_summary
    - 'Predict-ion "Some Pref"':
        formula: '=IF(%# Students%>0,SUMIF(%*%,%summary_field%,PredPref)/%# Students%,"")'
        format: single_percent_centered
        width: 9.43h
        label_format: bold_red_center_wrap
        cond_format: single_percent_centered_solid_bottom
        sum_formula: '=SUMPRODUCT(|# Students|,|Predict-ion "Some Pref"|)/@# Students@'
        sum_format: single_percent_centered_summary
