inputs:
    AllColleges: inputs/all_colleges.csv
    CollegeListLookup: inputs/college_list_lookup.csv
    CustomWeights: inputs/custom_weights.csv
    StandardWeights: inputs/standard_weights.csv
    Strategies: inputs/strategy_definitions.csv
    StudentTargets: inputs/targets_by_strategy.csv
    current_applications: current_applications.csv
    current_roster: current_students.csv

output_file:
    root_name: Weekly Report
    date_format: '%m_%d_%Y' # for strftime function

all_campuses: # campuses to try if "all" selected
    - Noble
    - Pritzker
    - Rauner
    - Golder
    - RoweClark
    - Comer
    - UIC
    - Bulls
    - Muchin
    - Johnson
    - DRW
    - Hansberry
    - Baker
    - Butler

sort_students: # how to sort the students tab for the single student views
    Standard: '=%Counselor%&%LastFirst%'
    UIC: '=%Counselor%&%Cohort%&%LastFirst%'
    Golder: '=%Cohort%&%Counselor%&%LastFirst%'

category_labels: # this is for customizing certain odds/class language
    Standard:
        TargetGR: Target
        IdealGR: Ideal
        BelowGR: Below Target
        FarBelowGR: Far Below Target
        SureThing: Sure Thing
        Secure: Secure
        Safety: Safety
        Match: Match
        Reach: Reach
        Longshot: Longshot
        HailMary: Hail Mary
    Golder:
        TargetGR: Expected
        IdealGR: Ideal
        BelowGR: Below Expected
        FarBelowGR: Far Below Expected
        SureThing: Sure Thing
        Secure: Secure
        Safety: Safety
        Match: Match
        Reach: Reach
        Longshot: Longshot
        HailMary: Hail Mary
    RoweClark:
        TargetGR: Average
        IdealGR: Ideal
        BelowGR: Minimum
        FarBelowGR: Subpar
        SureThing: Sure Thing
        Secure: Secure
        Safety: Safety
        Match: Match
        Reach: Reach
        Longshot: Longshot
        HailMary: Hail Mary

###################################################
# Students tab details
students_columns:
    - Campus:
        formula: tbl:Campus
        format: yellow
        width: 10h
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_wrap
        cond_format: dash_bottom
    - EFC:
        formula: tbl:EFC
        format: left_normal_text
        width: 6
        head_text: ''
        head_format: left_normal_text
        label_format: bold_wrap
        cond_format: dash_bottom
    - SpEd:
        formula: tbl:SpEd
        format: yellow
        width: 6h
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_wrap
        cond_format: dash_bottom
    - LastFirst:
        formula: tbl:LastFirst
        format: yellow
        width: 16h
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_wrap
        cond_format: dash_bottom
    - StudentID:
        formula: <id>
        format: left_normal_text
        width: 12
        head_text: ''
        head_format: left_normal_text
        label_format: bold_wrap
        cond_format: dash_bottom
    - Last:
        formula: tbl:Last
        format: left_normal_text
        width: 12
        head_text: ''
        head_format: blue
        label_format: bold_blue_wrap
        cond_format: dash_bottom
    - First:
        formula: tbl:First
        format: right
        width: 12
        head_text: ''
        head_format: blue_right
        label_format: bold_blue_wrap_right
        cond_format: dash_bottom_right
    - GPA:
        formula: tbl:GPA
        format: two_point_centered
        width: 5.57
        head_text: 'Student profile'
        head_format: bold_olive_underline
        label_format: bold_olive_center_wrap
        cond_format: dash_bottom
    - ACT:
        formula: tbl:ACT
        format: centered
        width: 4.43
        head_text: ''
        head_format: bold_olive_underline
        label_format: bold_olive_center_wrap
        cond_format: dash_bottom
    - 'Race / Eth':
        formula: 'tbl:Race/ Eth'
        format: centered
        width: 4.86
        head_text: ''
        head_format: bold_olive_underline
        label_format: bold_olive_center_wrap
        cond_format: dash_bottom
    - Stra-tegy:
        formula: '=IF(AND(%GPA%<>0,%ACT%<>0),IF(ISNUMBER(VLOOKUP(TEXT(MAX(FLOOR(%GPA%*10,1)/10,1.5),"0.0")&":"&MAX(%ACT%,12),StrategyLookup,4,FALSE)),VLOOKUP(TEXT(MAX(FLOOR(%GPA%*10,1)/10,1.5),"0.0")&":"&MAX(%ACT%,12),StrategyLookup,4,FALSE),"TBD"),"TBD")'
        format: centered
        width: 4.29
        head_text: ''
        head_format: bold_olive_underline
        label_format: bold_olive_center_wrap
        cond_format: dash_bottom
    - '=TargetGRLabel&" Grad Rate"':
        formula: '=IF(ISNUMBER(%Stra-tegy%),VLOOKUP(IF(OR(%Stra-tegy%=4,%Stra-tegy%=5),%Stra-tegy%&IF(%GPA%>=3,"+","<"),%Stra-tegy%&""),TargetLookup,IF(%EFC%=-1,6,IF(OR(%Race / Eth%="W",%Race / Eth%="A"),4,2)),FALSE),"TBD")'
        format: percent_centered
        width: 7.57
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_center_wrap
        cond_format: dash_bottom
    - '=IdealGRLabel&" Grad Rate"':
        formula: '=IF(ISNUMBER(%Stra-tegy%),VLOOKUP(IF(OR(%Stra-tegy%=4,%Stra-tegy%=5),%Stra-tegy%&IF(%GPA%>=3,"+","<"),%Stra-tegy%&""),TargetLookup,IF(%EFC%=-1,7,IF(OR(%Race / Eth%="W",%Race / Eth%="A"),5,3)),FALSE),"TBD")'
        format: percent_centered
        width: 7.57
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_center_wrap
        cond_format: dash_bottom
    - Cohort:
        formula: tbl:Cohort
        format: yellow
        width: 7.57h
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_center_wrap
        cond_format: dash_bottom
    - Advisor:
        formula: tbl:Advisor
        format: left_normal_text
        width: 7.57
        head_text: ''
        head_format: yellow
        label_format: bold_yellow_center_wrap
        cond_format: dash_bottom
    - Counselor:
        formula: tbl:Counselor
        format: left_normal_text
        width: 16.29
        head_text: ''
        head_format: blue
        label_format: bold_blue_wrap
        cond_format: dash_bottom
    - SortCode:
        formula: cfg:sort_students
        format: left_normal_text
        width: 16.29h
        head_text: ''
        head_format: blue
        label_format: bold_blue_wrap
        cond_format: dash_bottom

student_names: #Excel named ranges based on these columns
    LastFirst: LastFirst
    KidIDs: StudentID
    KidGPAs: GPA
    KidACTs: ACT
    KidRace: 'Race / Eth'
    Strats: Stra-tegy
    StudentTargets: '=TargetGRLabel&" Grad Rate"'
    ReachStudentTargets: '=IdealGRLabel&" Grad Rate"'
    Advisors: Advisor
    Counselor: Counselor



###################################################
# Applications tab details
app_fields: # fields to grab from the Naviance application data in order
    - Campus
    - hs_student_id
    - last_name
    - first_name
    - middle_name
    - collegename
    - stage
    - type
    - result_code
    - attending
    - waitlisted
    - deferred
    - comments
    - NCES

app_format_catch: # formats to add back to the Naviance application data
    collegename: bold_orange
    Campus: bold_blue
    hs_student_id: bold_blue
    last_name: bold_blue
    first_name: bold_blue
    NCES: bold_orange

applications_calculations: # definitions for calculated columns in order
    - Barron's:
        formula: =INDEX(AllCollegeBarrons,MATCH(%NCES%,AllCollegeNCES,0))
        format: bold_orange
    - GPA:
        formula: =INDEX(KidGPAs,MATCH(%hs_student_id%,KidIDs,0))
        format: bold_blue
    - ACT:
        formula: =INDEX(KidACTs,MATCH(%hs_student_id%,KidIDs,0))
        format: bold_blue
    - Strategy:
        formula: =INDEX(Strats,MATCH(%hs_student_id%,KidIDs,0))
        format: bold_blue
    - Race:
        formula: =INDEX(KidRace,MATCH(%hs_student_id%,KidIDs,0))
        format: bold_blue
    - TargetGR:
        formula: =INDEX(StudentTargets,MATCH(%hs_student_id%,KidIDs,0))
        format: bold_blue
    - IdealGR:
        formula: =INDEX(ReachStudentTargets,MATCH(%hs_student_id%,KidIDs,0))
        format: bold_blue
    - PartnerBump:
        formula: =IF(OR(%comments%="Posse"),1,0)
        format: bold_orange
    - 6yr_all:
        formula: =IF(ISNUMBER(INDEX(AllCollegeGR, MATCH(%NCES%,AllCollegeNCES,0))),ROUND(INDEX(AllCollegeGR, MATCH(%NCES%,AllCollegeNCES,0))+%PartnerBump%*IF(INDEX(AllCollegeGR, MATCH(%NCES%,AllCollegeNCES,0))>0.7,(1-INDEX(AllCollegeGR, MATCH(%NCES%,AllCollegeNCES,0)))/2,0.15),2),INDEX(AllCollegeGR, MATCH(%NCES%,AllCollegeNCES,0)))
        format: bold_orange
    - 6yr_AA/H:
        formula: =IF(ISNUMBER(INDEX(AllCollegeAAHGR, MATCH(%NCES%,AllCollegeNCES,0))),ROUND(INDEX(AllCollegeAAHGR, MATCH(%NCES%,AllCollegeNCES,0))+%PartnerBump%*IF(INDEX(AllCollegeAAHGR, MATCH(%NCES%,AllCollegeNCES,0))>0.7,(1-INDEX(AllCollegeAAHGR, MATCH(%NCES%,AllCollegeNCES,0)))/2,0.15),2),INDEX(AllCollegeAAHGR, MATCH(%NCES%,AllCollegeNCES,0)))
        format: bold_orange
    - ACT25/50:
        formula: =IF(OR(%Race%="H",%Race%="B"),INDEX(AllCollegeACT25, MATCH(%NCES%,AllCollegeNCES,0)),INDEX(AllCollegeACT50, MATCH(%NCES%,AllCollegeNCES,0)))
        format: bold_orange
    - GPAcoefB:
        formula: =INDEX(CustomWeightsGPA,MATCH(%Race%&":"&%NCES%,CustomWeightsIndex,0))
        format: bold_yellow
    - ACTcoefB:
        formula: =INDEX(CustomWeightsACT,MATCH(%Race%&":"&%NCES%,CustomWeightsIndex,0))
        format: bold_yellow
    - InterceptB:
        formula: =INDEX(CustomWeightsIntercept,MATCH(%Race%&":"&%NCES%,CustomWeightsIndex,0))
        format: bold_yellow
    - LogitB:
        formula: =%GPAcoefB%*%GPA%+%ACTcoefB%*%ACT%+%InterceptB%
        format: bold_yellow
    - GPAcoefA:
        formula: =INDEX(CoefficientsGPA,MATCH(%Race%&":"&%Barron's%,CoefficientsIndex,0))
        format: bold_olive
    - ACTcoefA:
        formula: =INDEX(CoefficientsACT,MATCH(%Race%&":"&%Barron's%,CoefficientsIndex,0))
        format: bold_olive
    - InterceptA:
        formula: =INDEX(CoefficientsIntercept,MATCH(%Race%&":"&%Barron's%,CoefficientsIndex,0))
        format: bold_olive
    - LogitA:
        formula: =%GPAcoefA%*%GPA%+(%ACT%-%ACT25/50%)*%ACTcoefA%+%InterceptA%
        format: bold_olive
    - FinalLogit:
        formula: =IF(ISNUMBER(%LogitB%),%LogitB%,%LogitA%)
        format: bold_olive
    - Odds:
        formula: =IF(ISNUMBER(%FinalLogit%),IF(ISNUMBER(%GPAcoefA%),IF(AND(%GPAcoefA%=1,%ACTcoefA%=1,%InterceptA%=1),100,ROUND(100*EXP(%FinalLogit%)/(1+EXP(%FinalLogit%)),2)),ROUND(100*EXP(%FinalLogit%)/(1+EXP(%FinalLogit%)),2)),IF(ISTEXT(%Barron's%),IF(LEFT(%Barron's%,1)="2",100,"N/A"),"N/A"))
        format: bold_olive
    - Class:
        formula: =IF(ISNUMBER(%Odds%),IF(%Odds%>=99,IF(OR(%Strategy%=10,%Strategy%=11),"Match","Sure Thing"),IF(%Odds%>=95,"Secure",IF(%Odds%>=80,"Safety",IF(%Odds%>=50,"Match",IF(%Odds%>=20,"Reach",IF(%Odds%>=10,"Longshot","Hail Mary")))))),"Other")
        format: bold_olive
    - Result:
        formula: =IF(OR(%result_code%="accepted",%result_code%="cond. accept",%result_code%="summer admit"),IF(%attending%="yes","CHOICE!","Accepted!"),IF(%result_code%="denied","Denied",IF(%waitlisted%=1,"Waitlist",IF(%deferred%=1,"Deferred",IF(%stage%="pending","Pending",IF(OR(%stage%="initial materials submitted",%stage%="mid-year submitted",%stage%="final submitted"),"Submitted",IF(%type%="interest","Interest","?")))))))
        format: bold_olive

    - ReachOrBetter:
        formula: =IF(OR(%Class%="Reach",%Class%="Longshot",%Class%="Hail Mary"),1,0)
        format: bold_yellow
    - MatchOrBetter:
        formula: =IF(OR(%ReachOrBetter%=1,%Class%="Match"),1,0)
        format: bold_yellow
    - 6yrAll/AAH_forSorting:
        formula: =IF(OR(%Race%="H",%Race%="B"),IF(ISNUMBER(%6yr_AA/H%),ROUND(%6yr_AA/H%,2),0),IF(ISNUMBER(%6yr_all%),ROUND(%6yr_all%,2),0))
        format: bold_yellow
    - TGROrBetter:
        formula: =IF(%6yrAll/AAH_forSorting%>=%TargetGR%,1,0)
        format: bold_yellow
    - IGROrBetter:
        formula: =IF(%6yrAll/AAH_forSorting%>=%IdealGR%,1,0)
        format: bold_yellow
    - InverseOdds:
        formula: =1-%Odds%/100
        format: bold_yellow
    - MatchOrBetterMult:
        formula: =IF(%MatchOrBetter%=1,%InverseOdds%,1)
        format: bold_yellow
    - ReachOrBetterMult:
        formula: =IF(%ReachOrBetter%=1,%InverseOdds%,1)
        format: bold_yellow
    - TGRorBetterMult:
        formula: =IF(AND(%TGROrBetter%=1,ISNUMBER(%InverseOdds%)),$%InverseOdds%,1)
        format: bold_yellow
    - IGRorBetterMult:
        formula: =IF(AND(%IGROrBetter%=1,ISNUMBER(%InverseOdds%)),$%InverseOdds%,1)
        format: bold_yellow
    - MoneyYesNo:
        formula: =IF(ISNUMBER(%6yr_AA/H%),INDEX(AllCollegeMoney, MATCH(%NCES%,AllCollegeNCES,0)),0)
        format: bold_orange
    - TGRorBetterMoneyMult:
        formula: =IF(AND(%TGROrBetter%=1,ISNUMBER(%InverseOdds%),%MoneyYesNo%=1),$%InverseOdds%,1)
        format: bold_yellow
    - IGRorBetterMoneyMult:
        formula: =IF(AND(%IGROrBetter%=1,ISNUMBER(%InverseOdds%),%MoneyYesNo%=1),$%InverseOdds%,1)
        format: bold_yellow
    - SGRMult:
        formula: =IF(ISNUMBER(%TargetGR%),IF(AND(%6yrAll/AAH_forSorting%<%TargetGR%,%6yrAll/AAH_forSorting%>(%TargetGR%-0.08),ISNUMBER(%InverseOdds%)),%InverseOdds%,1),1)
        format: bold_yellow
    - ILPub:
        formula: =IF(ISNUMBER(%6yr_AA/H%),INDEX(AllCollegeILPub, MATCH(%NCES%,AllCollegeNCES,0)),0)
        format: bold_yellow
    # These odds fields all need to be consecutive
    - Reach:
        formula: =IF(%Class%="Reach",%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Match:
        formula: =IF(%Class%="Match",%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Safety:
        formula: =IF(%Class%="Safety",%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Secure:
        formula: =IF(%Class%="Secure",%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Sure_Thing:
        formula: =IF(%Class%="Sure Thing",%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Reach-:
        formula: =MAX(%Reach%:%Sure_Thing%)
        format: bold_yellow
    - Match-:
        formula: =MAX(%Match%:%Sure_Thing%)
        format: bold_yellow
    - Safety-:
        formula: =MAX(%Safety%:%Sure_Thing%)
        format: bold_yellow
    - ReachMoney:
        formula: =IF(AND(%Class%="Reach",%MoneyYesNo%=1),%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    # These Odds Money fields all need to be consecutive
    - MatchMoney:
        formula: =IF(AND(%Class%="Match",%MoneyYesNo%=1),%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - SafetyMoney:
        formula: =IF(AND(%Class%="Safety",%MoneyYesNo%=1),%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - SecureMoney:
        formula: =IF(AND(%Class%="Secure",%MoneyYesNo%=1),%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Sure_ThingMoney:
        formula: =IF(AND(%Class%="Sure Thing",%MoneyYesNo%=1),%6yrAll/AAH_forSorting%,0)
        format: bold_yellow
    - Reach-Money:
        formula: =MAX(%ReachMoney%:%Sure_ThingMoney%)
        format: bold_yellow
    - Match-Money:
        formula: =MAX(%MatchMoney%:%Sure_ThingMoney%)
        format: bold_yellow
    - Safety-Money:
        formula: =MAX(%SafetyMoney%:%Sure_ThingMoney%)
        format: bold_yellow
    - MoneyChicago:
        formula: =IF(ISNUMBER(%6yr_AA/H%),INDEX(AllCollegeChicago, MATCH(%NCES%,AllCollegeNCES,0))*%MoneyYesNo%,0)
        format: bold_yellow


      
           

application_names: #Excel named ranges based on these columns
    CollegeNames: collegename
    Stages: stage
    Students: hs_student_id
    NCESids: NCES
    Barrons: Barron's
    AllGradRates: 6yr_all
    GradRates: 6yr_AA/H
    Odds: Odds
    Classes: Class
    Results: Result
    MGRcount: TGROrBetter
    RGRcount: IGROrBetter
    MatchMult: MatchOrBetterMult
    ReachMult: ReachOrBetterMult
    MGRMult: TGRorBetterMult
    RGRMult: IGRorBetterMult
    MoneyYesNo: MoneyYesNo
    MGRMoneyMult: TGRorBetterMoneyMult
    RGRMoneyMult: IGRorBetterMoneyMult
    SGRMult: SGRMult
    ILPublic: ILPub
    ReachUnder: Reach-
    MatchUnder: Match-
    SafetyUnder: Safety-
    ReachUnderMoney: Reach-Money
    MatchUnderMoney: Match-Money
    SafetyUnderMoney: Safety-Money
    MoneyChicago: MoneyChicago

##################################################3
## Excel Formats
##################################################3
excel_formats:
    # non-colored number formats
    percent_fmt:
        num_format: 0.0%
    percent_centered:
        num_format: 0.0%
        align: center
    percent_bold_fmt:
        num_format: 0.0%
        bold: True
    two_point_centered:
        num_format: '0.00'
        align: center

    # non-colored non-number formats
    centered:
        align: center
    right:
        right: 1
    bold:
        bold: True
        align: left
    bold_wrap:
        bold: True
        align: left
        text_wrap: True
        bottom: 1
    left_normal_text:
        bold: False
        align: left
        top: 0
        left: 0
        right: 0
        bottom: 0
    dash_bottom:
        bottom: 3
    dash_bottom_right:
        bottom: 3
        right: 1

    # olive
    bold_olive:
        bold: True
        bg_color: "#C4D79B"
    bold_olive_underline:
        bold: True
        bg_color: "#C4D79B"
        align: left
        underline: True
    bold_olive_center_wrap:
        bold: True
        bg_color: "#C4D79B"
        align: center
        text_wrap: True
        bottom: 1
        valign: top

    # yellow
    yellow:
        bg_color: "#FFFF00"
    bold_yellow:
        bg_color: "#FFFF00"
        bold: True
    percent_yellow:
        bg_color: "#FFFF00"
        num_format: 0.0%
    bold_yellow_wrap:
        bg_color: "#FFFF00"
        bold: True
        align: left
        text_wrap: True
        bottom: 1
    bold_yellow_center_wrap:
        bold: True
        align: center
        bg_color: "#FFFF00"
        text_wrap: True
        bottom: 1
        valign: top

    # blue
    blue:
        bg_color: "#92CDDC"
    bold_blue:
        bg_color: "#92CDDC"
        bold: True
    blue_right:
        bg_color: "#92CDDC"
        right: 1
    bold_blue_wrap:
        bg_color: "#92CDDC"
        bold: True
        align: left
        text_wrap: True
        bottom: 1
    bold_blue_wrap_right:
        bg_color: "#92CDDC"
        bold: True
        align: left
        text_wrap: True
        bottom: 1
        right: 1

    # orange
    bold_orange:
        bg_color: "#FFC000"
        bold: True
